### PR TITLE
use peerDependency for tslint

### PR DESCRIPTION
**Pull request by ashwinr**
fixes https://github.com/panuhorsmalahti/gulp-tslint/issues/26

### CODE REVIEW

**Comment by panuhorsmalahti** [comment]
I think that with npm v3 and this change the user always needs to manually specify the tslint version, which is not user friendly. I wonder if there's another solution..

**Comment by krtr** [comment]
Maybe give user option to pass tslint module just like gulp-typescript which has option to pass typescript 
https://www.npmjs.com/package/gulp-typescript#typescript-version

**Comment by ashwinr** [comment]
@panuhorsmalahti I can close this PR if you want to do it the way @krtr suggests. A lot of people want to use tslint@next for react/1.6 and gulp-tslint is currently in the way.

**Comment by panuhorsmalahti** [comment]
I'll implement the option to pass the tslint module.

**Comment by panuhorsmalahti** [comment]
I released a new version of gulp-tslint with the new tslint option. Check the readme for more information. Thanks for the feature suggestion!

**Pull request closed without merging**
