### PR TITLE
Format and colorize output

### PR DESCRIPTION
**Pull request by LeoTT**
The current output could visually benefit by leaving out repetitive information, using colors to highlight information and rearranging the structure with columns.
## Before
previous

## After
after

### CODE REVIEW

**Comment by panuhorsmalahti** [comment]
How do these colors work in e.g. Jenkins console log output? IIRC it can cause garbage characters to be displayed (e.g. http://stackoverflow.com/questions/15146432/jenkins-console-output-has-these-strange-characters-from-grunt-command-31m39m ) - and the same issue might exist for other tools. Might be necessary to make the colors optional at least - maybe even default to disabled..

**Comment by panuhorsmalahti** [comment]
Rebase the five commits to one.

**Comment by LeoTT** [comment]
Good point. I made a little research. The colors are fairly safe, because `chalk`(the module that does the actual colorizing) tries to determine whether the terminal is able to use colors before printing them with [supports-colors](https://github.com/chalk/supports-color).
Also tested it with dumb terminal(which does not support ANSI) and sure enough the output is not colorized.

Jenkins also does not support ANSI by default. From what I've read it seems like `chalk` does recognize that(I have not tested that yet though).

There may be exotic cases where `chalk` thinks the terminal could handle ANSI when it actually cannot.

Either way I fully agree with making the colors optional. As of now I made it default to disabled, although I consider the cases where the terminal cannot display the colors(and chalk does not recognize that) to be rare.

**Comment by chrismbarr** [comment]
Doesn't TSlint already do this?  I have colorized output depending on which formatted I use.

```ts
gulp.src("//app/**/*.ts")
    .pipe(plumber())
    .pipe(tsLint({
        formatter: "stylish"
    }))
    .pipe(tsLint.report());
```

image

**Comment by panuhorsmalahti** [comment]
Closing as unnecessary for now

**Pull request closed without merging**
